/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/app-header.vue')['default']
    AppNavigationDrawer: typeof import('./components/app-navigation-drawer.vue')['default']
    ComplexBtn: typeof import('./components/complex-btn.vue')['default']
    CrudEditor: typeof import('./components/crud-editor.vue')['default']
    PageLayout: typeof import('./components/page-layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
