/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/layout/app-header.vue')['default']
    AppNavigationDrawer: typeof import('./components/layout/app-navigation-drawer.vue')['default']
    ComplexBtn: typeof import('./components/buttons/complex-btn.vue')['default']
    CrudInput: typeof import('./components/inputs/crud-input.vue')['default']
    CrudInputBtns: typeof import('./components/inputs/crud-input-btns.vue')['default']
    PageLayout: typeof import('./components/layout/page-layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
